# Generated by Django 5.2 on 2025-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
